### ISSUE TITLE
Errors in Console (Cannot read property 'isValid' of undefined)

### ISSUE THREAD

**Issue by Raghava-47** [PredixDev/px-calendar-picker#10]
we are using the px-calendar-picker in APM component. for one of the use case while loading this polymer component we are getting the below error logs in console. it is happening only in chrome not in other browsers. we investigate the issue in  **px-calendar-cell.html** and found that the filed "displayDate" is initialized as undefined and will be initialized after notifying the observers(_updateDate) associated with this property. till it get initialized this error logs keeps occurring.

polymer-mini.html:2128 Uncaught TypeError: Cannot read property 'isValid' of undefined
    at HTMLElement.<anonymous> (px-calendar-cell.html:99)
    at Debouncer.complete (polymer-mini.html:2167)
    at Debouncer.boundComplete (polymer-mini.html:2144)
    at Object._atEndOfMicrotask (polymer-mini.html:2122)
    at MutationObserver.window.MutationObserver.observe.characterData (polymer-mini.html:2137)

(anonymous) @ px-calendar-cell.html:99
complete @ polymer-mini.html:2167
Debouncer.boundComplete @ polymer-mini.html:2144
_atEndOfMicrotask @ polymer-mini.html:2122
window.MutationObserver.observe.characterData @ polymer-mini.html:2137

**Comment by randyaskin** [comment]
I believe this would have been resolved by the undefined check in the Polymer 2 hybrid upgrade. Please reopen / let us know if that is not the case.
