### ISSUE TITLE
px-datetime-range-submitted is not triggered

### ISSUE THREAD

**Issue by musti2** [PredixDev/px-calendar-picker#5]
Hi team,

The event 'px-datetime-range-submitted' is not triggered at all when setting a range as specified in the documentation.

The only event i could see after inspection is 'px-cell-date-selected' - however, there is no certain way to differentiate if it's a start or end date.

**Comment by Menkhaus-ge** [comment]
Fixed with v0.5.1
Thank you for you feedback.
