### ISSUE TITLE
Getting a 404/missing icon on demo.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-calendar-picker#9]
Getting a 404 on the calendar-picker demo page. Noticed it while testing localization.
 
## Version/Environment:

- Calendar-picker version: 0.7.0 running locally.  
- Doesn't happen on predix-ui.com

## Screenshot:
![calendar_picker_404](https://cloud.githubusercontent.com/assets/10835611/26417031/cc4520e2-406c-11e7-9fff-d27f74b61b93.png)

**Comment by randyaskin** [comment]
No longer an issue in the latest prerelease version of the component.
